name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          # Replace this line with the command or script you want to execute
          echo "Hello, World!"
